AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple REST API application instance only'

Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/canonical/ubuntu/server/noble/stable/current/amd64/hvm/ebs-gp3/ami-id'
  KeyName:
    Type: String
    Description: EC2 Key Pair name (optional, for SSH access)
    Default: ''

Conditions:
  HasKeyName: !Not [!Equals [!Ref KeyName, '']]


Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !ImportValue InstanceProfile
      KeyName: !If [HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !ImportValue InstanceSecurityGroup
          SubnetId: !ImportValue PublicSubnet
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Update system
          yum update -y

      Tags:
        - Key: Name
          Value: SuperlistsAppInstance
Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
    Export:
      Name: SuperlistsAppInstanceId

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: SuperlistsAppPublicIP

  PublicDNS:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName
    Export:
      Name: SuperlistsAppPublicDNS

  ApiUrl:
    Description: URL to access the REST API
    Value: !Sub 'http://${EC2Instance.PublicIp}:8080'
    Export:
      Name: SuperlistsAppUrl