# Generated by Django 6.0 on 2026-01-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_alter_item_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["id"]},
        ),
    ]
